fun failable(): Num? {
    if 0 > 5 {
        fail 1
    }

    return 1
}

let a = failable() failed: echo "Failed"

if a is Num: echo "Succeeded"
